#!/usr/bin/perl -w

#Copyright (C) <2015>  <Huguenin Loïs>

#   Torrtux is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.

#   Torrtux is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.



#Call of the standard modules
use lib '/usr/share/torrtux';
use LWP::UserAgent;
use strict;
use feature "switch";
use Term::ANSIColor qw(:constants);
use Getopt::Long;
$Term::ANSIColor::AUTORESET = 1;
Getopt::Long::Configure( "bundling" );
no warnings 'experimental::smartmatch';



#Call of the program's modules
use Getinfos;
use Getdetails;
use Torrent;
use Tools;
use Configfile;

#Variables declaration

#Hash table to sort preferences in arguments
my %table_sort = ( "date" => "3",
	"se" => "7",
	"le" => "9",
	"user" => "12",
	"size" => "5");

my ($retour, $inc, $research, $sort, $sort_pref) = (1, 0, '', '7');
my $prog = "torrtux";
my $compact = read_filerc()->compact;

#Retrieve options gived in argument
GetOptions("sort=s" => \$sort_pref);

if(defined($sort_pref))
{
    $sort = $table_sort{$sort_pref};
}

#Get the research in arguments if exist
foreach(@ARGV)
{
    $research .= $_ . ' ';
}
while($retour){

    $retour = main();
}
print CLEAR BLUE BOLD "New research ? (y/N)". BOLD YELLOW "\n==> ";
my $newr = get_input();
if($newr eq "y"){
    exec $prog;
	die "$prog not find in $ENV{PATH}";
}

sub header{
    my $return;
    if($compact){
	$return = BOLD YELLOW "Num|".BOLD GREEN "SE|".BOLD RED "LE|".WHITE "Genre|".CLEAR BLUE BOLD"Name|".DARK GREEN "Author";
    }
    else{
	$return = "Num\tSE\tLE\tGenre\tName\n"; 
    }
    return $return;
}


#Main function 
sub main{

#Initiation variables
    my ($page, $i, $torrent) = ('',0, Torrent->new());
    my (@pages, @urls_torrents, @urls_details);

#Call of the function of config file
    # read_filerc();

#Retrieve the research
    if(!($research)){
        print CLEAR BLUE BOLD "PIRATE SEARCH : ";
	$research = get_input();
    }

#Get the web page
    $page = page_dwnld($research, 1, '', $sort); 
    print header();

    $i = get_and_display_infos($page, \@urls_torrents, \@urls_details, $compact);
    if ($i == 0)
    {
	print "No torrents found\n";
	exit(1);
    }

#Call choices function
    if((choices(\@urls_torrents, \@urls_details)) and ($page)){
	return 1;
    }
    else
    {
	return 0;
    }

}

#Function for choosing action after research
sub choices
{
    my $choice;
    my $urls_torrents = shift;
    my $urls_details = shift;

    print BOLD YELLOW "\n==>" . CLEAR BLUE BOLD " Details (m) | display and copy the magnet link (c) | next page (t) | page no. (p) | new search (s) ?\n" . BOLD YELLOW "==> ";

    $choice = get_input();

    given ($choice) {
	when(/m/) {
	    if(display_details($urls_details, $urls_torrents))
	    {
		return 1;
	    }
	}
	when(/c/){
	    display_magnetic_link($urls_torrents,$urls_details);
	}
	when(/t/){
	    return 1;
	}
	when(/p/){
	    print BOLD YELLOW "\n==> " . CLEAR BLUE BOLD "Which page ?" . BOLD YELLOW "\n==> " . RESET;
	    $page_n = get_input();
	    return 1;
	}
	when(/s/){
	    exec $prog;
		die "$prog not found in $ENV{PATH}";
	}
	default{
	    print BOLD BLUE "Not a possible choice, quitting..."; 
	    exit(0);
	}
    }
    return 0;
}

